#loader multiblocked

import mods.multiblocked.MBDRegistry;
import mods.multiblocked.definition.ControllerDefinition;
import mods.multiblocked.definition.ComponentDefinition;
import mods.multiblocked.recipe.RecipeMap;
import mods.multiblocked.functions.ISetupRecipe;
import mods.multiblocked.recipe.RecipeLogic;
import mods.multiblocked.recipe.Recipe;
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

import crafttweaker.text.ITextComponent;

var definition as ComponentDefinition = MBDRegistry.getDefinition("multiblocked:mud_kiln");
var kiln = definition as ControllerDefinition;


//val coke as IIngredient = (<metaitem:gemCoke>|<metaitem:dustCoke>) as IIngredient;
//val coal as IIngredient = (<ore:gemCoal>.firstItem|<metaitem:dustCoal>) as IIngredient;
//val charcoal as IIngredient = (<ore:gemCharcoal>.firstItem*2|<metaitem:dustCharcoal>*2) as IIngredient;

val steelMap as IItemStack[][] = [
	[<metaitem:ingotSteel>*2,<metaitem:ingotWroughtIron>*2,<metaitem:gemCoke>],
	[<metaitem:ingotSteel>,<metaitem:ingotWroughtIron>,<ore:gemCoal>.firstItem],
	[<metaitem:ingotSteel>,<metaitem:ingotWroughtIron>,<ore:gemCharcoal>.firstItem*2],
] as IItemStack[][];

for item in steelMap {
kiln.recipeMap.start()
    .duration(60*20)
    .inputItems(item[1], item[2])
    .outputItems(item[0])
    .buildAndRegister();
}


val oreMap as IItemStack[][] = [
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcopyrite_1:5>],
[<minecraft:iron_ingot>,<gregtech:ore_yellow_limonite_1:4>],
[<gregtech:meta_ingot:109>,<gregtech:ore_thorium_1>],
[<gregtech:meta_ingot:55>,<gregtech:ore_galena_1:2>],
[<gregtech:meta_ingot:69>,<gregtech:ore_pentlandite_1:1>],
[<gregtech:meta_ingot:25>,<gregtech:ore_bornite_1:5>],
[<minecraft:iron_ingot>,<gregtech:ore_pyrite_0>],
[<gregtech:meta_ingot:25>,<libvulpes:ore0:4>],
[<gregtech:meta_ingot:69>,<gregtech:ore_garnierite_1:3>],
[<gregtech:meta_ingot:25>,<gregtech:ore_malachite_1:2>],
[<gregtech:meta_ingot:25>,<gregtech:ore_copper_1:2>],
[<minecraft:iron_ingot>,<gregtech:ore_banded_iron_0>],
[<gregtech:meta_ingot:25>,<gregtech:ore_bornite_1:2>],
[<minecraft:iron_ingot>,<gregtech:ore_iron_1:3>],
[<gregtech:meta_ingot:25>,<gregtech:ore_bornite_1>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_granitic_mineral_sand_0:1>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_granitic_mineral_sand_0:2>],
[<gregtech:meta_ingot:80>,<gregtech:ore_platinum_1:3>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenite_1:3>],
[<gregtech:meta_ingot:112>,<lucraftcore:ore_tin>],
[<gregtech:meta_ingot:69>,<gregtech:ore_pentlandite_1:5>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobaltite_1:4>],
[<gregtech:meta_ingot:122>,<gregtech:ore_sphalerite_1:4>],
[<gregtech:meta_ingot:61>,<gregtech:ore_pyrolusite_1:3>],
[<gregtech:meta_ingot:4>,<gregtech:ore_stibnite_0>],
[<minecraft:iron_ingot>,<gregtech:ore_basaltic_mineral_sand_1:2>],
[<gregtech:meta_ingot:100> * 2,<gregtech:ore_silver_0:1>],
[<gregtech:meta_ingot:112> * 4,<gregtech:ore_cassiterite_sand_0:2>],
[<gregtech:meta_ingot:122>,<gregtech:ore_sphalerite_1>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobaltite_1:2>],
[<gregtech:meta_ingot:112>,<gregtech:ore_tin_1>],
[<thebetweenlands:items_misc:11>,<gregtech:ore_syrmorite_1:1>],
[<gregtech:meta_ingot:55>,<gregtech:ore_lead_0>],
[<gregtech:meta_ingot:109> * 2,<gregtech:ore_thorium_0:2>],
[<gregtech:meta_ingot:109>,<gregtech:ore_thorium_1:5>],
[<thebetweenlands:octine_ingot> * 2,<gregtech:ore_octine_0:1>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_1:4>],
[<minecraft:iron_ingot>,<gregtech:ore_pyrite_1:5>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenite_1:4>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenum_1:3>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobalt_1>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobaltite_1:5>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenite_0>],
[<gregtech:meta_ingot:25>,<gregtech:ore_malachite_1:1>],
[<gregtech:meta_ingot:55>,<gregtech:ore_galena_1:1>],
[<gregtech:meta_ingot:80> * 2,<gregtech:ore_platinum_0:2>],
[<minecraft:iron_ingot>,<gregtech:ore_iron_1:4>],
[<gregtech:meta_ingot:122> * 2,<gregtech:ore_sphalerite_0:1>],
[<gregtech:meta_ingot:109>,<nuclearcraft:ore:3>],
[<minecraft:iron_ingot>,<industrialrenewal:orevein_hematite>],
[<gregtech:meta_ingot:55>,<gregtech:ore_lead_1:5>],
[<gregtech:meta_ingot:10> * 2,<gregtech:ore_beryllium_0:1>],
[<gregtech:meta_ingot:122>,<gregtech:ore_sphalerite_1:3>],
[<minecraft:iron_ingot>,<gregtech:ore_basaltic_mineral_sand_1:3>],
[<gregtech:meta_ingot:69>,<gregtech:ore_garnierite_1:2>],
[<gregtech:meta_ingot:25>,<gregtech:ore_copper_1:5>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcocite_1>],
[<gregtech:meta_ingot:23> * 2,<gregtech:ore_cobalt_0:2>],
[<gregtech:meta_ingot:55>,<gregtech:ore_galena_1:5>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_banded_iron_0:1>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_sand_1:5>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobalt_1:2>],
[<thebetweenlands:items_misc:11> * 2,<gregtech:ore_syrmorite_0:1>],
[<gregtech:meta_ingot:61>,<gregtech:ore_pyrolusite_1:4>],
[<gregtech:meta_ingot:55>,<gregtech:ore_galena_1:3>],
[<gregtech:meta_ingot:23> * 2,<gregtech:ore_cobalt_0:1>],
[<nuclearcraft:ingot:7>,<nuclearcraft:ore:7>],
[<gregtech:meta_ingot:55>,<nuclearcraft:ore:2>],
[<gregtech:meta_ingot:122> * 2,<gregtech:ore_sphalerite_0:2>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcopyrite_1>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_banded_iron_0:2>],
[<gregtech:meta_ingot:10>,<gregtech:ore_beryllium_1:5>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenum_1:1>],
[<gregtech:meta_ingot:10>,<gregtech:ore_beryllium_1:4>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_sand_1:2>],
[<minecraft:iron_ingot>,<gregtech:ore_iron_1>],
[<gregtech:meta_ingot:25>,<nuclearcraft:ore>],
[<gregtech:meta_ingot:61>,<gregtech:ore_pyrolusite_1:1>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_sand_1:3>],
[<gregtech:meta_ingot:109> * 2,<gregtech:ore_thorium_0:1>],
[<gregtech:meta_ingot:25>,<gregtech:ore_copper_1:1>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_chalcocite_0:1>],
[<gregtech:meta_ingot:81> * 2,<gregtech:ore_plutonium_0:2>],
[<gregtech:meta_ingot:25>,<gregtech:ore_tetrahedrite_1:4>],
[<gregtech:meta_ingot:55> * 2,<gregtech:ore_lead_0:2>],
[<minecraft:iron_ingot>,<gregtech:ore_pyrite_1:4>],
[<minecraft:iron_ingot>,<gregtech:ore_yellow_limonite_1:1>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_1:5>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenite_1:5>],
[<minecraft:iron_ingot>,<gregtech:ore_magnetite_1:5>],
[<gregtech:meta_ingot:69> * 2,<gregtech:ore_nickel_0:1>],
[<minecraft:iron_ingot>,<gregtech:ore_pyrite_1:1>],
[<gregtech:meta_ingot:10>,<gregtech:ore_beryllium_0>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_magnetite_0:1>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_brown_limonite_0:2>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobalt_1:5>],
[<minecraft:iron_ingot>,<gregtech:ore_granitic_mineral_sand_1:1>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcopyrite_1:4>],
[<minecraft:gold_ingot>,<gregtech:ore_gold_1>],
[<gregtech:meta_ingot:100>,<gregtech:ore_silver_1:5>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_1:3>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_yellow_limonite_0:2>],
[<gregtech:meta_ingot:81>,<gregtech:ore_plutonium_1:4>],
[<thebetweenlands:items_misc:11>,<gregtech:ore_syrmorite_1:3>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcopyrite_1:3>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcopyrite_1:2>],
[<minecraft:iron_ingot>,<industrialrenewal:chunk_hematite>],
[<gregtech:meta_ingot:81>,<gregtech:ore_plutonium_1:1>],
[<gregtech:meta_ingot:55> * 2,<gregtech:ore_lead_0:1>],
[<gregtech:meta_ingot:122>,<gregtech:ore_sphalerite_0>],
[<gregtech:meta_ingot:112>,<gregtech:ore_tin_1:2>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcopyrite_1:1>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_tetrahedrite_0:2>],
[<gregtech:meta_ingot:4>,<gregtech:ore_stibnite_1:1>],
[<gregtech:meta_ingot:55>,<gregtech:ore_lead_1:1>],
[<minecraft:iron_ingot>,<gregtech:ore_yellow_limonite_1:5>],
[<gregtech:meta_ingot:55> * 2,<gregtech:ore_galena_0:1>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_iron_0:2>],
[<minecraft:iron_ingot>,<gregtech:ore_brown_limonite_1:5>],
[<gregtech:meta_ingot:100>,<gregtech:ore_silver_1>],
[<gregtech:meta_ingot:112>,<libvulpes:ore0:5>],
[<gregtech:meta_ingot:100>,<gregtech:ore_silver_1:1>],
[<gregtech:meta_ingot:81> * 2,<gregtech:ore_plutonium_0:1>],
[<minecraft:gold_ingot> * 2,<gregtech:ore_gold_0:2>],
[<gregtech:meta_ingot:69>,<gregtech:ore_garnierite_1:5>],
[<gregtech:meta_ingot:69>,<gregtech:ore_garnierite_1:4>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_iron_0:1>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcocite_1:2>],
[<gregtech:meta_ingot:61>,<gregtech:ore_pyrolusite_0>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_pyrite_0:2>],
[<minecraft:iron_ingot>,<gregtech:ore_iron_0>],
[<gregtech:meta_ingot:25>,<gregtech:ore_copper_1>],
[<gregtech:meta_ingot:100>,<gregtech:ore_silver_1:2>],
[<minecraft:iron_ingot>,<gregtech:ore_banded_iron_1:2>],
[<gregtech:meta_ingot:25>,<lucraftcore:ore_copper>],
[<gregtech:meta_ingot:64> * 2,<gregtech:ore_molybdenite_0:2>],
[<minecraft:gold_ingot>,<gregtech:ore_gold_1:2>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_1>],
[<gregtech:meta_ingot:69>,<gregtech:ore_pentlandite_0>],
[<minecraft:iron_ingot>,<gregtech:ore_brown_limonite_1:4>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcocite_0>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcocite_1:5>],
[<gregtech:meta_ingot:122>,<gregtech:ore_sphalerite_1:5>],
[<gregtech:meta_ingot:25>,<gregtech:ore_malachite_0>],
[<gregtech:meta_ingot:81>,<gregtech:ore_plutonium_0>],
[<gregtech:meta_ingot:64> * 2,<gregtech:ore_molybdenum_0:2>],
[<minecraft:iron_ingot>,<gregtech:ore_magnetite_1:2>],
[<gregtech:meta_ingot:122>,<gregtech:ore_sphalerite_1:1>],
[<minecraft:gold_ingot>,<gregtech:ore_gold_1:3>],
[<gregtech:meta_ingot:112>,<gregtech:ore_tin_1:5>],
[<minecraft:iron_ingot>,<gregtech:ore_banded_iron_1:4>],
[<gregtech:meta_ingot:112>,<gregtech:ore_tin_1:1>],
[<thebetweenlands:octine_ingot> * 2,<gregtech:ore_octine_0:2>],
[<minecraft:iron_ingot>,<gregtech:ore_yellow_limonite_1:3>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenum_1:2>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_sand_1:4>],
[<minecraft:iron_ingot>,<gregtech:ore_yellow_limonite_1:2>],
[<gregtech:meta_ingot:55>,<gregtech:ore_galena_1>],
[<minecraft:iron_ingot>,<gregtech:ore_yellow_limonite_1>],
[<gregtech:meta_ingot:69> * 2,<gregtech:ore_garnierite_0:1>],
[<gregtech:meta_ingot:69>,<gregtech:ore_garnierite_1>],
[<minecraft:gold_ingot>,<gregtech:ore_gold_1:1>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenite_1:2>],
[<minecraft:iron_ingot>,<gregtech:ore_brown_limonite_1:1>],
[<nuclearcraft:ingot:5>,<nuclearcraft:ore:5>],
[<gregtech:meta_ingot:69> * 2,<gregtech:ore_pentlandite_0:2>],
[<gregtech:meta_ingot:69>,<gregtech:ore_nickel_1>],
[<minecraft:iron_ingot>,<gregtech:ore_magnetite_0>],
[<gregtech:meta_ingot:4>,<gregtech:ore_stibnite_1:3>],
[<minecraft:iron_ingot>,<gregtech:ore_pyrite_1:2>],
[<minecraft:gold_ingot>,<erebus:ore_gold>],
[<minecraft:iron_ingot>,<gregtech:ore_magnetite_1:3>],
[<gregtech:meta_ingot:80>,<gregtech:ore_platinum_1:5>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobaltite_1:1>],
[<thebetweenlands:octine_ingot>,<gregtech:ore_octine_1:5>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_basaltic_mineral_sand_0:1>],
[<minecraft:iron_ingot>,<erebus:ore_iron>],
[<gregtech:meta_ingot:55>,<gregtech:ore_galena_1:4>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobaltite_0>],
[<thebetweenlands:octine_ingot>,<gregtech:ore_octine_0>],
[<gregtech:meta_ingot:55>,<gregtech:ore_lead_1:4>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcocite_1:1>],
[<gregtech:meta_ingot:10>,<gregtech:ore_beryllium_1>],
[<gregtech:meta_ingot:109>,<gregtech:ore_thorium_1:2>],
[<gregtech:meta_ingot:25>,<gregtech:ore_malachite_1:5>],
[<gregtech:meta_ingot:100> * 2,<gregtech:ore_silver_0:2>],
[<minecraft:gold_ingot>,<gregtech:ore_gold_1:4>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_copper_0:2>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_chalcocite_0:2>],
[<gregtech:meta_ingot:55>,<lucraftcore:ore_lead>],
[<gregtech:meta_ingot:25>,<gregtech:ore_copper_1:3>],
[<minecraft:iron_ingot>,<gregtech:ore_basaltic_mineral_sand_1>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_bornite_0:1>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcopyrite_0>],
[<gregtech:meta_ingot:81>,<gregtech:ore_plutonium_1>],
[<gregtech:meta_ingot:100>,<gregtech:ore_silver_1:3>],
[<gregtech:meta_ingot:25>,<gregtech:ore_malachite_1:3>],
[<minecraft:iron_ingot>,<gregtech:ore_granitic_mineral_sand_1:3>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_tin_0:2>],
[<gregtech:meta_ingot:69>,<gregtech:ore_pentlandite_1:3>],
[<minecraft:gold_ingot>,<gregtech:ore_gold_1:5>],
[<gregtech:meta_ingot:109>,<gregtech:ore_thorium_1:4>],
[<gregtech:meta_ingot:25>,<gregtech:ore_malachite_1:4>],
[<minecraft:iron_ingot>,<gregtech:ore_banded_iron_1:1>],
[<gregtech:meta_ingot:112>,<gregtech:ore_tin_1:4>],
[<gregtech:meta_ingot:69>,<gregtech:ore_nickel_0>],
[<gregtech:meta_ingot:80>,<gregtech:ore_platinum_0>],
[<minecraft:iron_ingot>,<gregtech:ore_banded_iron_1>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_magnetite_0:2>],
[<gregtech:meta_ingot:112> * 4,<gregtech:ore_cassiterite_0:2>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenum_1>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenum_1:4>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_1:1>],
[<gregtech:meta_ingot:64> * 2,<gregtech:ore_molybdenite_0:1>],
[<minecraft:iron_ingot>,<gregtech:ore_magnetite_1:4>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobalt_1:4>],
[<gregtech:meta_ingot:25>,<gregtech:ore_tetrahedrite_1:2>],
[<minecraft:iron_ingot>,<gregtech:ore_granitic_mineral_sand_1:2>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobalt_1:1>],
[<minecraft:iron_ingot>,<gregtech:ore_brown_limonite_0>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcocite_1:3>],
[<minecraft:iron_ingot>,<gregtech:ore_iron_1:1>],
[<gregtech:meta_ingot:25>,<gregtech:ore_bornite_1:3>],
[<gregtech:meta_ingot:69> * 2,<gregtech:ore_nickel_0:2>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_chalcopyrite_0:2>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_chalcopyrite_0:1>],
[<gregtech:meta_ingot:10>,<gregtech:ore_beryllium_1:3>],
[<minecraft:iron_ingot>,<gregtech:ore_basaltic_mineral_sand_0>],
[<gregtech:meta_ingot:112>,<gregtech:ore_tin_0>],
[<gregtech:meta_ingot:25>,<gregtech:ore_tetrahedrite_0>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobalt_1:3>],
[<gregtech:meta_ingot:112> * 4,<gregtech:ore_cassiterite_sand_0:1>],
[<minecraft:iron_ingot>,<gregtech:ore_pyrite_1>],
[<minecraft:iron_ingot>,<gregtech:ore_iron_1:5>],
[<minecraft:iron_ingot>,<gregtech:ore_yellow_limonite_0>],
[<gregtech:meta_ingot:4> * 2,<gregtech:ore_stibnite_0:1>],
[<minecraft:iron_ingot>,<gregtech:ore_magnetite_1>],
[<gregtech:meta_ingot:25>,<gregtech:ore_tetrahedrite_1:5>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_yellow_limonite_0:1>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_tetrahedrite_0:1>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_brown_limonite_0:1>],
[<minecraft:iron_ingot>,<gregtech:ore_basaltic_mineral_sand_1:1>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenite_1>],
[<gregtech:meta_ingot:64> * 2,<gregtech:ore_molybdenum_0:1>],
[<gregtech:meta_ingot:80>,<gregtech:ore_platinum_1:2>],
[<gregtech:meta_ingot:69>,<gregtech:ore_nickel_1:5>],
[<thebetweenlands:items_misc:11>,<gregtech:ore_syrmorite_1:5>],
[<gregtech:meta_ingot:23> * 2,<gregtech:ore_cobaltite_0:1>],
[<gregtech:meta_ingot:81>,<gregtech:ore_plutonium_1:2>],
[<gregtech:meta_ingot:109>,<gregtech:ore_thorium_1:1>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobaltite_1:3>],
[<gregtech:meta_ingot:61>,<gregtech:ore_pyrolusite_1>],
[<gregtech:meta_ingot:112>,<nuclearcraft:ore:1>],
[<gregtech:meta_ingot:4>,<gregtech:ore_stibnite_1>],
[<minecraft:iron_ingot>,<gregtech:ore_iron_1:2>],
[<gregtech:meta_ingot:25>,<gregtech:ore_tetrahedrite_1>],
[<thebetweenlands:octine_ingot>,<thebetweenlands:octine_ore>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobalt_0>],
[<thebetweenlands:octine_ingot>,<gregtech:ore_octine_1:3>],
[<gregtech:meta_ingot:25>,<gregtech:ore_tetrahedrite_1:1>],
[<minecraft:iron_ingot>,<gregtech:ore_granitic_mineral_sand_1:5>],
[<gregtech:meta_ingot:69>,<gregtech:ore_garnierite_1:1>],
[<gregtech:meta_ingot:109>,<gregtech:ore_thorium_1:3>],
[<thebetweenlands:items_misc:11>,<gregtech:ore_syrmorite_0>],
[<gregtech:meta_ingot:61> * 2,<gregtech:ore_pyrolusite_0:2>],
[<gregtech:meta_ingot:69>,<gregtech:ore_garnierite_0>],
[<minecraft:iron_ingot>,<gregtech:ore_brown_limonite_1>],
[<gregtech:meta_ingot:80>,<gregtech:ore_platinum_1:4>],
[<minecraft:iron_ingot>,<gregtech:ore_brown_limonite_1:2>],
[<minecraft:iron_ingot>,<gregtech:ore_banded_iron_1:5>],
[<gregtech:meta_ingot:4>,<gregtech:ore_stibnite_1:5>],
[<gregtech:meta_ingot:4>,<gregtech:ore_stibnite_1:4>],
[<thebetweenlands:items_misc:11>,<gregtech:ore_syrmorite_1:2>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenite_1:1>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_bornite_0:2>],
[<gregtech:meta_ingot:69>,<gregtech:ore_pentlandite_1>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenum_0>],
[<gregtech:meta_ingot:61> * 2,<gregtech:ore_pyrolusite_0:1>],
[<minecraft:iron_ingot>,<gregtech:ore_granitic_mineral_sand_1>],
[<gregtech:meta_ingot:61>,<gregtech:ore_pyrolusite_1:5>],
[<minecraft:iron_ingot>,<gregtech:ore_basaltic_mineral_sand_1:4>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_pyrite_0:1>],
[<gregtech:meta_ingot:100>,<gregtech:ore_silver_0>],
[<gregtech:meta_ingot:25>,<gregtech:ore_copper_1:4>],
[<gregtech:meta_ingot:25>,<gregtech:ore_copper_0>],
[<gregtech:meta_ingot:55>,<gregtech:ore_galena_0>],
[<minecraft:iron_ingot>,<gregtech:ore_granitic_mineral_sand_1:4>],
[<gregtech:meta_ingot:10>,<gregtech:ore_beryllium_1:1>],
[<gregtech:meta_ingot:69> * 2,<gregtech:ore_pentlandite_0:1>],
[<minecraft:iron_ingot>,<gregtech:ore_brown_limonite_1:3>],
[<thebetweenlands:items_misc:11> * 2,<gregtech:ore_syrmorite_0:2>],
[<gregtech:meta_ingot:10> * 2,<gregtech:ore_beryllium_0:2>],
[<thebetweenlands:items_misc:11>,<gregtech:ore_syrmorite_1:4>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_0>],
[<gregtech:meta_ingot:100>,<gregtech:ore_silver_1:4>],
[<minecraft:iron_ingot>,<gregtech:ore_granitic_mineral_sand_0>],
[<thebetweenlands:octine_ingot>,<gregtech:ore_octine_1:4>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_sand_1:1>],
[<gregtech:meta_ingot:80>,<gregtech:ore_platinum_1>],
[<gregtech:meta_ingot:80> * 2,<gregtech:ore_platinum_0:1>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_tin_0:1>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_1:2>],
[<thebetweenlands:octine_ingot>,<gregtech:ore_octine_1>],
[<minecraft:gold_ingot> * 2,<gregtech:ore_gold_0:1>],
[<gregtech:meta_ingot:25>,<gregtech:ore_bornite_1:4>],
[<gregtech:meta_ingot:4> * 2,<gregtech:ore_stibnite_0:2>],
[<gregtech:meta_ingot:55> * 2,<gregtech:ore_galena_0:2>],
[<gregtech:meta_ingot:69>,<gregtech:ore_pentlandite_1:4>],
[<gregtech:meta_ingot:122>,<gregtech:ore_sphalerite_1:2>],
[<gregtech:meta_ingot:69>,<lucraftcore:ore_nickel>],
[<gregtech:meta_ingot:23>,<gregtech:ore_cobaltite_1>],
[<gregtech:meta_ingot:69>,<gregtech:ore_nickel_1:1>],
[<minecraft:iron_ingot> * 2,<gregtech:ore_basaltic_mineral_sand_0:2>],
[<gregtech:meta_ingot:25>,<gregtech:ore_malachite_1>],
[<thebetweenlands:items_misc:11>,<gregtech:ore_syrmorite_1>],
[<thebetweenlands:items_misc:11>,<thebetweenlands:syrmorite_ore>],
[<gregtech:meta_ingot:55>,<gregtech:ore_lead_1:3>],
[<gregtech:meta_ingot:23> * 2,<gregtech:ore_cobaltite_0:2>],
[<gregtech:meta_ingot:69>,<gregtech:ore_nickel_1:2>],
[<gregtech:meta_ingot:81>,<gregtech:ore_plutonium_1:3>],
[<gregtech:meta_ingot:55>,<gregtech:ore_lead_1>],
[<gregtech:meta_ingot:112>,<gregtech:ore_tin_1:3>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_malachite_0:2>],
[<gregtech:meta_ingot:25>,<gregtech:ore_bornite_0>],
[<gregtech:meta_ingot:4>,<gregtech:ore_stibnite_1:2>],
[<gregtech:meta_ingot:69>,<gregtech:ore_nickel_1:4>],
[<minecraft:iron_ingot>,<gregtech:ore_magnetite_1:1>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_copper_0:1>],
[<gregtech:meta_ingot:112> * 4,<gregtech:ore_cassiterite_0:1>],
[<minecraft:iron_ingot>,<gregtech:ore_basaltic_mineral_sand_1:5>],
[<gregtech:meta_ingot:25>,<gregtech:ore_tetrahedrite_1:3>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_sand_1>],
[<gregtech:meta_ingot:80>,<gregtech:ore_platinum_1:1>],
[<minecraft:iron_ingot>,<gregtech:ore_pyrite_1:3>],
[<gregtech:meta_ingot:100>,<lucraftcore:ore_silver>],
[<gregtech:meta_ingot:55>,<gregtech:ore_lead_1:2>],
[<gregtech:meta_ingot:109>,<gregtech:ore_thorium_0>],
[<gregtech:meta_ingot:61>,<gregtech:ore_pyrolusite_1:2>],
[<gregtech:meta_ingot:69> * 2,<gregtech:ore_garnierite_0:2>],
[<gregtech:meta_ingot:10>,<gregtech:ore_beryllium_1:2>],
[<minecraft:iron_ingot>,<gregtech:ore_banded_iron_1:3>],
[<gregtech:meta_ingot:112> * 2,<gregtech:ore_cassiterite_sand_0>],
[<minecraft:gold_ingot>,<gregtech:ore_gold_0>],
[<gregtech:meta_ingot:69>,<gregtech:ore_nickel_1:3>],
[<gregtech:meta_ingot:69>,<gregtech:ore_pentlandite_1:2>],
[<gregtech:meta_ingot:25> * 2,<gregtech:ore_malachite_0:1>],
[<thebetweenlands:octine_ingot>,<gregtech:ore_octine_1:1>],
[<gregtech:meta_ingot:64>,<gregtech:ore_molybdenum_1:5>],
[<gregtech:meta_ingot:25>,<gregtech:ore_chalcocite_1:4>],
[<thebetweenlands:octine_ingot>,<gregtech:ore_octine_1:2>],
[<gregtech:meta_ingot:81>,<gregtech:ore_plutonium_1:5>],
[<gregtech:meta_ingot:25>,<gregtech:ore_bornite_1:1>],
] as IItemStack[][];

for item in oreMap {
kiln.recipeMap.start()
    .duration(5*20)
    .inputItems(item[1], <thebetweenlands:items_misc:27>, <metaitem:dustSmallBlastFuel>)
    .outputItems(item[0])
    .outputItems(0.33, item[0])
    .buildAndRegister();
}